# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/spotseeker -r win-x64 -p:PublishSingleFile=true --self-contained false
    - name: print
      run: ls ${{env.DOTNET_ROOT}}/spotseeker
    - name: Upload to artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: SpotSeeker
        path: ${{env.DOTNET_ROOT}}/spotseeker    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v1.0.${{github.run_number}}
        release_name: Release v1.0.${{github.run_number}}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-artifact@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: SpotSeeker.exe
        path: ${{env.DOTNET_ROOT}}/spotseeker/SpotSeeker.exe
  
